<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.2.2 setup script
 * Date: Sun, 01 Jun 2014 23:29:17 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: biotagger [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'biotagger';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'QAZwsx098';

/* End of servers configuration */

$cfg['blowfish_secret'] = '538bb70b5d7a81.93494095';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>